#!/usr/bin/env bash

key=0
ESCAPE_KEY=9

screensize=`xdpyinfo | grep -i dimensions: | sed 's/[^0-9]*pixels.*(.*).*//' | sed 's/[^0-9x]*//'`

ffmpeg -y -f x11grab -s $screensize -i $DISPLAY -vframes 1 /tmp/screen_locked.png

while read line
do
    if [[ "$line" =~ "detail:" ]]; then
        key=$(echo $line | sed 's/detail: //')
        break
    fi
done < <(xinput test-xi2 --root)

killall i3lock

if [[ "$key" == "$ESCAPE_KEY" ]]; then
    xdotool key "Super_L+L"
else
    ffmpeg -f video4linux2 -i /dev/video0 -y -vf "scale=$screensize" -frames 1 /tmp/screen_locked.png
    i3lock -i /tmp/screen_locked.png
fi

rm -f /tmp/screen_locked.png
