#!/usr/bin/env bash

# See https://github.com/RealOrangeOne/pranklock

ESCAPE_KEY=9
TEMP_SCREEN_FILE=$(mktemp XXXXXXXXXX.png)
VIDEO_DEV=${1:-/dev/video0}

screensize=$(xdpyinfo | grep -i dimensions: | sed 's/[^0-9]*pixels.*(.*).*//' | sed 's/[^0-9x]*//')

ffmpeg -y -f x11grab -s "$screensize" -i "$DISPLAY" -vframes 1 "$TEMP_SCREEN_FILE"

i3lock -i "$TEMP_SCREEN_FILE" -p default &

key=0
while read -r line
do
    if [[ "$line" =~ "detail:" ]]; then
        key=${line//detail: /}
        break
    fi
done < <(xinput test-xi2 --root)

if [[ "$key" == "$ESCAPE_KEY" ]]; then
    killall i3lock
    xdotool key "Super_L+l"  # Delegate locking to something else
else
    ffmpeg -f video4linux2 -video_size hd720 -i "$VIDEO_DEV" -y -vf "scale=$screensize" -frames 1 "$TEMP_SCREEN_FILE"
    killall i3lock
    i3lock -i "$TEMP_SCREEN_FILE"
fi

rm -f "$TEMP_SCREEN_FILE"
